// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Project struct {
	Name string
}

type ProjectTimer struct {
	ProjectName  string
	StartSeconds int64
	StopSeconds  int64
}
