// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const deleteTimers = `-- name: DeleteTimers :exec
DELETE FROM project_timers
WHERE project_name = ?
`

func (q *Queries) DeleteTimers(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, deleteTimers, projectName)
	return err
}

const getProject = `-- name: GetProject :many
SELECT p.name, t.start_seconds, t.stop_seconds
FROM projects AS p
JOIN project_timers AS t ON p.name = t.project_name
WHERE p.name = ?
ORDER BY
    t.start_seconds DESC,
    t.stop_seconds DESC
`

type GetProjectRow struct {
	Name         string
	StartSeconds int64
	StopSeconds  int64
}

func (q *Queries) GetProject(ctx context.Context, name string) ([]GetProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getProject, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectRow
	for rows.Next() {
		var i GetProjectRow
		if err := rows.Scan(&i.Name, &i.StartSeconds, &i.StopSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingProjects = `-- name: ListOngoingProjects :many
SELECT project_name AS name
FROM project_timers
WHERE stop_seconds = -1
ORDER BY name ASC
`

func (q *Queries) ListOngoingProjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT name
FROM projects
ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoppedProjects = `-- name: ListStoppedProjects :many
SELECT DISTINCT t1.project_name
FROM project_timers t1
LEFT OUTER JOIN project_timers t2
ON t1.project_name = t2.project_name
AND t2.stop_seconds = -1
WHERE t2.project_name IS NULL
ORDER BY t1.project_name
`

func (q *Queries) ListStoppedProjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStoppedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var project_name string
		if err := rows.Scan(&project_name); err != nil {
			return nil, err
		}
		items = append(items, project_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTimer = `-- name: StartTimer :exec
INSERT INTO project_timers (
	project_name, start_seconds, stop_seconds
) VALUES (
	?, unixepoch('now'), -1
)
`

func (q *Queries) StartTimer(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, startTimer, projectName)
	return err
}

const stopTimer = `-- name: StopTimer :one
UPDATE project_timers
SET stop_seconds = unixepoch('now')
WHERE project_name = ? AND stop_seconds = -1
RETURNING project_name, start_seconds, stop_seconds
`

func (q *Queries) StopTimer(ctx context.Context, projectName string) (ProjectTimer, error) {
	row := q.db.QueryRowContext(ctx, stopTimer, projectName)
	var i ProjectTimer
	err := row.Scan(&i.ProjectName, &i.StartSeconds, &i.StopSeconds)
	return i, err
}
